### ISSUE TITLE
Jenkins bake fails due to waiter error

### ISSUE THREAD

**Issue by jaamut** [NitorCreations/nameless-deploy-tools#25]
I'm facing an issue where the waiter fails due to timeout when baking Jenkins image. It seems to fail approx in ten minutes while the AMI is still `Pending` state in AWS.

The short version of the error output is
```
botocore.exceptions.WaiterError: Waiter image_available failed: Max attempts exceeded
```

I believe the timeout could be increased on `bake-image.yml` like it has been done on `bake-win-image.yml`. Doubling the wait time could resolve my issue. What do you think?

**Comment by psiniemi** [comment]
Increasing the timeout is ok since I don't know of any specific pathology that the timeout would prevent. Could also, at the same time of increasing the default, make it configurable.

**Comment by jaamut** [comment]
Thanks. These changed would be more than welcome! 🚀

**Comment by psiniemi** [comment]
1.262 has IMAGE_WAIT parameter that can override the defaults that are now 1200s for linux and still 1800s for Windows.

https://github.com/NitorCreations/nameless-deploy-tools/blob/master/docs/parameters.md#image_wait

**Comment by jaamut** [comment]
I tried with the default and got this error

```
"msg": "argument 'wait_timeout' is of type <class 'str'> and we were unable to convert to int: <class 'str'> cannot be converted to an int"
```

**Comment by psiniemi** [comment]
Can you add the full job output?

**Comment by psiniemi** [comment]
Nevermind. Think I spotted the bug

**Comment by psiniemi** [comment]
1.263 Fixes this I hope

**Comment by jaamut** [comment]
Okay, thanks! Btw, I noticed another thing: Is this line lacking the backslash?
https://github.com/NitorCreations/nameless-deploy-tools/blob/ebaee09ebee9004db622fdfa4483d5d5c4ac58eb/n_utils/includes/bake-image.sh#L323

Because I also saw this on the output
```
/var/lib/jenkins/jenkins-home/.local/lib/python3.9/site-packages/n_utils/includes/bake-image.sh: line 321: -e: command not found
+ echo 'AMI baking failed'
```
