### ISSUE TITLE
Bake-jenkins fails with version 1.272

### ISSUE THREAD

**Issue by misacorn** [NitorCreations/nameless-deploy-tools#29]
Running bake-jenkins  fails with version 1.272 with errors:

```
"failures": [
        "No package xmlstarlet available."
    ],
```

```
mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master
```

These same messages also occur with version 1.264. How can we fix this?

**Comment by psiniemi** [comment]
xmlstarlet is not a package that is installed by default. So it's part of your bake and has been added there based on your needs which I can't even begin to guess. You can troubleshoot the repository it is supposed to come from or replace it with something else that matches your needs.

**Comment by psiniemi** [comment]
I'm closing this now since it's a specific case for one environment, I can help privately but it's not appropriate publicly. You can email me or contact me on twitter/linkedin or what suits you best.
